import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Travel Buddy",
  description: "Generated by Human",
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
          <main className="container">{children}</main>
      </body>
    </html>
  );
};

export default Layout;
