import "../styles/globals.css";
import AppContextProvider from "@/context/AppContext";

export const metadata = {
  title: "Travel Buddy",
  description: "Generated by Human",
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
};

export default Layout;
